"""
Проект №1
ІПЗ - 12, Петраківський Данило


The gallows

    It's a PvE game where player is to recognize the random word generated by AI. Player gradually
guess each letter. If recognition fails, AI complements the hanged man picture; if it's finished,
player loses. Unlimited attempts to play are available as well.
"""
from os import system, name
from time import sleep
from random import choice


def read_hanged_men():
    """
    Return the list of the hanged men states, used for word recognizing process display.
    """
    with open('res/hanged_men.txt') as file:
        return file.read().split('\n\n')


def read_words():
    """
    Return the list of the words to recognize.
    """
    with open('res/words.txt') as file:
        return [word for line in file.readlines() for word in line.split()]


HANGED_MEN = read_hanged_men()
WORDS = read_words()
YES = 'так'
NO = 'ні'


class Word:
    """
    Word implementation, which stands for word choice and recognition.

    >>> Word().choice != ''
    True
    """
    choice = choice(WORDS)
    letter_index = 0
    recognition = ''

    def is_recognized(self):
        """
        Check if player has recognized the whole word.
        """
        return self.choice == self.recognition

    def check(self, letter):
        """
        Check if player has recognized a regular letter in the word.
        """
        check = self.choice[self.letter_index] == letter
        if check:
            self.recognition += letter
            self.letter_index += 1
        return check


class HangedMan:
    """
    Hanged man class, which stands for shape depicting and word recognition process display.

    >>> HangedMan().shape != ''
    True
    """
    index = 0
    shape = HANGED_MEN[index]

    def is_finished(self):
        """
        Check if all attempts to recognize the word are exhausted.
        """
        return self.shape == HANGED_MEN[len(HANGED_MEN) - 1]

    def complement(self):
        """
        Complement hanged man shape if letter isn't recognized.
        """
        self.index += 1
        self.shape = HANGED_MEN[self.index]


def start():
    """
    Main function which is program's entry point.

    >>> len(HANGED_MEN) >= 2
    True
    >>> len(WORDS) >= 1
    True
    """
    clear()
    print_intro()
    in_game = True
    while in_game:
        play()
        if read_decision() == NO:
            in_game = False
    clear()


def clear():
    """
    Clear console.
    """
    system('cls' if name == 'nt' else 'clear')


def print_intro():
    """
    Print intro.
    """
    with open('res/intro.txt') as file:
        print(file.read())
        input('Натисніть Enter...')


def play():
    """
    Business logic function, where game process occurs.
    """
    make_time_delay()
    word = Word()
    hanged_man = HangedMan()
    while not (hanged_man.is_finished() or word.is_recognized()):
        print_progress(hanged_man.shape, word.recognition)
        if not word.check(input('Введіть літеру: ')[0]):
            hanged_man.complement()
            print('Хибне припущення! Спробуйте ще.')
    print_results(hanged_man, word.recognition)


def make_time_delay():
    """
    Make time delay before word choice.
    """
    print('\nЗагадаується слово...')
    sleep(2)
    clear()


def print_progress(shape, recognition):
    """
    Clear console, depict hanged man shape and recognized letters.
    """
    clear()
    print(shape)
    print('\n{}\n'.format(recognition))


def print_results(hanged_man, recognition):
    """
    Print final shape, recognition and message as well.
    """
    print_progress(hanged_man.shape, recognition)
    print('ВИ ПРОГРАЛИ!\n' if hanged_man.is_finished() else 'ВИ ПЕРЕМОГЛИ!\n')


def read_decision():
    """
    Read player's decision regards game continuation.
    """
    while True:
        decision = input('Бажаєте зіграти ще одну гру?({}/{}): '.format(YES, NO))
        if decision == YES or decision == NO:
            return decision
        print('Некоректне введення; спробуйте ще.')


if __name__ == '__main__':
    start()
